[package]
name = "wintap-netadaptercx-driver"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[package.metadata.wdk.driver-model]
driver-type = "KMDF"
kmdf-version-major = 1
target-kmdf-version-minor = 33

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[build-dependencies]
wdk-build.workspace = true

[dependencies]
netadaptercx-sys.workspace = true
wdk.workspace = true
wdk-alloc.workspace = true
wdk-panic.workspace = true
wdk-sys.workspace = true

[lints.rust]
unsafe_op_in_unsafe_fn = "forbid"

[lints.clippy]
undocumented_unsafe_blocks = "forbid"
